export const ADD_FLASH_MESSAGE         = 'ADD_FLASH_MESSAGE'
export const REMOVE_FLASH_MESSAGE      = 'REMOVE_FLASH_MESSAGE'
export const SET_CURRENT_USER          = 'SET_CURRENT_USER'
export const REMOVE_CURRENT_USER       = 'REMOVE_CURRENT_USER'
export const REMOVE_ALL_FLASH_MESSAGES = 'REMOVE_ALL_FLASH_MESSAGES'

export const REQUEST_QUIZZES = 'REQUEST_QUIZZES'
export const RECEIVE_QUIZZES = 'RECEIVE_QUIZZES'

export const POST_NEW_QUIZ    = 'POST_NEW_QUIZ'
export const SUCCESS_NEW_QUIZ = 'SUCCESS_NEW_QUIZ'
export const RECEIVE_NEW_QUIZ = 'RECEIVE_NEW_QUIZ'
